# Generated by Django 3.2.19 on 2024-11-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Labs Name')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
            ],
        ),
    ]
